//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapWebServiceConsumer.LemonWayWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LemonWayWS.LemonWayWebServiceSoap")]
    public interface LemonWayWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name FibonacciResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fibonacci", ReplyAction="*")]
        SoapWebServiceConsumer.LemonWayWS.FibonacciResponse Fibonacci(SoapWebServiceConsumer.LemonWayWS.FibonacciRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fibonacci", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapWebServiceConsumer.LemonWayWS.FibonacciResponse> FibonacciAsync(SoapWebServiceConsumer.LemonWayWS.FibonacciRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FibonacciRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Fibonacci", Namespace="http://tempuri.org/", Order=0)]
        public SoapWebServiceConsumer.LemonWayWS.FibonacciRequestBody Body;
        
        public FibonacciRequest() {
        }
        
        public FibonacciRequest(SoapWebServiceConsumer.LemonWayWS.FibonacciRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FibonacciRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int n;
        
        public FibonacciRequestBody() {
        }
        
        public FibonacciRequestBody(int n) {
            this.n = n;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FibonacciResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FibonacciResponse", Namespace="http://tempuri.org/", Order=0)]
        public SoapWebServiceConsumer.LemonWayWS.FibonacciResponseBody Body;
        
        public FibonacciResponse() {
        }
        
        public FibonacciResponse(SoapWebServiceConsumer.LemonWayWS.FibonacciResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FibonacciResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FibonacciResult;
        
        public FibonacciResponseBody() {
        }
        
        public FibonacciResponseBody(string FibonacciResult) {
            this.FibonacciResult = FibonacciResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LemonWayWebServiceSoapChannel : SoapWebServiceConsumer.LemonWayWS.LemonWayWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LemonWayWebServiceSoapClient : System.ServiceModel.ClientBase<SoapWebServiceConsumer.LemonWayWS.LemonWayWebServiceSoap>, SoapWebServiceConsumer.LemonWayWS.LemonWayWebServiceSoap {
        
        public LemonWayWebServiceSoapClient() {
        }
        
        public LemonWayWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LemonWayWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LemonWayWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LemonWayWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapWebServiceConsumer.LemonWayWS.FibonacciResponse SoapWebServiceConsumer.LemonWayWS.LemonWayWebServiceSoap.Fibonacci(SoapWebServiceConsumer.LemonWayWS.FibonacciRequest request) {
            return base.Channel.Fibonacci(request);
        }
        
        public string Fibonacci(int n) {
            SoapWebServiceConsumer.LemonWayWS.FibonacciRequest inValue = new SoapWebServiceConsumer.LemonWayWS.FibonacciRequest();
            inValue.Body = new SoapWebServiceConsumer.LemonWayWS.FibonacciRequestBody();
            inValue.Body.n = n;
            SoapWebServiceConsumer.LemonWayWS.FibonacciResponse retVal = ((SoapWebServiceConsumer.LemonWayWS.LemonWayWebServiceSoap)(this)).Fibonacci(inValue);
            return retVal.Body.FibonacciResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapWebServiceConsumer.LemonWayWS.FibonacciResponse> SoapWebServiceConsumer.LemonWayWS.LemonWayWebServiceSoap.FibonacciAsync(SoapWebServiceConsumer.LemonWayWS.FibonacciRequest request) {
            return base.Channel.FibonacciAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapWebServiceConsumer.LemonWayWS.FibonacciResponse> FibonacciAsync(int n) {
            SoapWebServiceConsumer.LemonWayWS.FibonacciRequest inValue = new SoapWebServiceConsumer.LemonWayWS.FibonacciRequest();
            inValue.Body = new SoapWebServiceConsumer.LemonWayWS.FibonacciRequestBody();
            inValue.Body.n = n;
            return ((SoapWebServiceConsumer.LemonWayWS.LemonWayWebServiceSoap)(this)).FibonacciAsync(inValue);
        }
    }
}
